CREATE TABLE "adventure_segment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "adventure_segment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text NOT NULL,
	"choice" text,
	"adventureId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "adventure" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "adventure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"prompt" text NOT NULL,
	"title" text,
	"imagePrompt" text,
	"imageUrl" text,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "adventure_segment" ADD CONSTRAINT "adventure_segment_adventureId_adventure_id_fk" FOREIGN KEY ("adventureId") REFERENCES "public"."adventure"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adventure" ADD CONSTRAINT "adventure_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "adventure_id_idx" ON "adventure_segment" USING btree ("adventureId");--> statement-breakpoint
CREATE INDEX "adventure_user_id_idx" ON "adventure" USING btree ("userId");